

public class EqualityTest {

      public static void main(String[] args) {

            String a, b;

            a = "MAYPFQLGFQDATSPIMEELLHFHDHTLMIVFLISSLVLYIISLMLTTKLTHTSTMDAQEVETIWTILPAIILILIALPSLRILYMMDEINSPSLTVKTMGHQWYWSYEYTDSEDLSFDSYMIPTQELKPGELRLLEVDNRVVLPMEVTIRVLISSEDVLHSWAVPSLGLKTDAIPGRLNQTTLMGTRPGLYYGQCSEICGSNHSFMPIVLELVPLAYFEKWSASM";

            b = "MAYPFQLGFQDATSPIMEELLHFHDHTLMIVFLISSLVLYIISLMLTTKLTHTSTMDAQEVETIWTILPAIILILIALPSLRILYMMDEINSPSLTVKTMGHQWYWSYEYTDSEDLSFDSYMIPTQELKPGELRLLEVDNRVVLPMEVTIRVLISSEDVLHSWAVPSLGLKTDAIPGRLNQTTLMGTRPGLYYGQCSEICGSNHSFMPIVLELVPLAYFEKWSASM";

            //b += "c";

            System.out.println("a: \"" + a + "\"");

            System.out.println("b: \"" + b + "\"");

            System.out.println("a == b: " + (a == b));

            System.out.println("a.equals(b): " + a.equals(b));

      }

}

